services:
  # Backend API Service
  api:
    build:
      context: ./apis
      dockerfile: Dockerfile
    container_name: turkmen-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./Turkmen-gala-apis/logs:/app/logs
      - ./Turkmen-gala-apis/uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_z1jsbUcT7Pdp@ep-twilight-haze-aehcj9za-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - ORIGIN=http://72.60.202.55:5001,http://72.60.202.55:5002
      - SECRET_KEY=a8f5b6d7c6e0f5a3b1c8d9e2f6a7b4c1d8e9f0a2b5c6d7e8f9a0b3c4d5e6f7a8
    networks:
      - turkmen-network

  # Frontend Website Service
  website:
    build:
      context: ./site
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://72.60.202.55:5000
    container_name: turkmen-website
    restart: unless-stopped
    ports:
      - "5001:80"
    depends_on:
      - api
    networks:
      - turkmen-network

  # CMS Service
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://72.60.202.55:5000
    container_name: turkmen-cms
    restart: unless-stopped
    ports:
      - "5002:80"
    depends_on:
      - api
    networks:
      - turkmen-network

volumes:
  api-logs:
    driver: local
  api-uploads:
    driver: local

networks:
  turkmen-network:
    driver: bridge